cc_test(
    name = 'option_test',
    srcs = [
        'option_test.cpp',
    ],
    copts = ['-std=c++14', '-pipe', '-Wall', '-Wextra'],
    deps = [
        '//:bipolar',
        '@gtest//:gtest_main',
    ]
)
