cc_test(
    name = 'option_test',
    srcs = [
        'option_test.cpp',
    ],
    copts = ['-std=c++17', '-pipe', '-Wall', '-Wextra'],
    deps = [
        '//:bipolar',
        '@gtest//:gtest_main',
    ]
)

cc_test(
    name = 'result_test',
    srcs = [
        'result_test.cpp',
    ],
    copts = ['-std=c++17', '-pipe', '-Wall', '-Wextra'],
    deps = [
        '//:bipolar',
        '@gtest//:gtest_main',
    ]
)

cc_test(
    name = 'traits_test',
    srcs = [
        'traits_test.cpp',
    ],
    copts = ['-std=c++17', '-pipe', '-Wall', '-Wextra'],
    deps = [
        '//:bipolar',
        '@gtest//:gtest_main',
    ]
)
