version: 2.1

commands:
  install-bazel:
    steps:
      - run:
          name: Installing bazel
          command: |
            bazel_version=2.0.0
            curl -OL https://github.com/bazelbuild/bazel/releases/download/${bazel_version}/bazel-${bazel_version}-installer-linux-x86_64.sh
            chmod +x bazel-${bazel_version}-installer-linux-x86_64.sh
            ./bazel-${bazel_version}-installer-linux-x86_64.sh
            rm ./bazel-${bazel_version}-installer-linux-x86_64.sh
            bazel --version

  sysinfo:
    steps:
      - run:
          name: System information
          command: |
            uname -a
            free -m
            gcc --version

jobs:
  build:
    docker:
      - image: gcc:9
    steps:
      - sysinfo
      - install-bazel
      - checkout
      - run:
          name: Building
          command: bazel build //... --jobs=4 # --jobs=auto will be OOM killed
      - run:
          name: Testing
          command: bazel test //... --test_tag_filters='-io_uring,-benchmark,-example' --test_output=errors

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
